<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Target
    Name="_ShinyMauiControlsAddImplementationAssemblyForXamlC"
    BeforeTargets="XamlC"
    Condition="'$(DesignTimeBuild)' != 'True' AND '@(MauiXaml)' != ''">
    <PropertyGroup>
      <_ShinyMauiControlsImplementationAssembly>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..\lib\$(TargetFramework)\Shiny.Maui.Controls.dll'))</_ShinyMauiControlsImplementationAssembly>
    </PropertyGroup>

    <ItemGroup Condition="Exists('$(_ShinyMauiControlsImplementationAssembly)')">
      <ReferencePath Include="$(_ShinyMauiControlsImplementationAssembly)" />
    </ItemGroup>
  </Target>
</Project>
