using System.Globalization;
using System.Text;

namespace Shiny.ThemeGen;

sealed record ThemeData(
    string Name,
    string Slug,
    string Description,
    IReadOnlyList<(string Role, string Hex)> Light,
    IReadOnlyList<(string Role, string Hex)> Dark,
    IReadOnlyList<(string Name, double Value)> Shape,
    IReadOnlyList<TypeToken> Type,
    TypeSpec TypeSpec,
    ElevationSpec ElevationSpec,
    IReadOnlyList<(string Name, string BoxShadow)> CssElevation,
    IReadOnlyList<(string Name, double Value)> Spacing,
    IReadOnlyList<(string Name, double Value)> Density,
    IReadOnlyList<(string Name, double Value)> State,
    IReadOnlyList<(string Name, double Value)> Border);

static class Emitter
{
    const string AutoGen = "// <auto-generated>\n// Generated by tools/ShinyThemeGen from /themes/*.json. DO NOT EDIT.\n// Edit the source JSON theme and re-run: dotnet run --project tools/ShinyThemeGen\n// </auto-generated>";
    const string AutoGenCss = "/* <auto-generated>\n   Generated by tools/ShinyThemeGen from /themes/*.json. DO NOT EDIT.\n   Edit the source JSON theme and re-run: dotnet run --project tools/ShinyThemeGen\n   </auto-generated> */";

    const string DefaultMonoStack = "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace";

    static string D(double v) => v.ToString("0.####", CultureInfo.InvariantCulture);
    static string Px(double v) => v == 0 ? "0px" : D(v) + "px";

    // ============================================================ Blazor CSS

    public static string Css(ThemeData t)
    {
        var sb = new StringBuilder();
        sb.Append(AutoGenCss).Append("\n\n");

        // Light scheme + all mode-independent tokens live in :root.
        sb.Append(":root {\n");
        // Native widgets (select, checkbox, date input, scrollbars, the popover backdrop) are painted
        // by the UA, not by our tokens - without this they stay in the light UA palette and a themed
        // dark control ends up hosting a stark white dropdown.
        sb.Append("    color-scheme: light;\n\n");
        sb.Append("    /* ===== Color (light) ===== */\n");
        foreach (var (role, hex) in t.Light)
            sb.Append($"    --shiny-color-{Tokens.Kebab(role)}: {hex};\n");

        sb.Append("\n    /* ===== Shape ===== */\n");
        foreach (var (name, val) in t.Shape)
            sb.Append($"    --shiny-shape-{Tokens.Kebab(name)}: {Px(val)};\n");

        sb.Append("\n    /* ===== Border widths ===== */\n");
        foreach (var (name, val) in t.Border)
            sb.Append($"    --shiny-border-{Tokens.Kebab(name)}: {Px(val)};\n");

        sb.Append("\n    /* ===== State ===== */\n");
        foreach (var (name, val) in t.State)
            sb.Append($"    --shiny-state-{Tokens.Kebab(name)}: {D(val)};\n");

        sb.Append("\n    /* ===== Density ===== */\n");
        foreach (var (name, val) in t.Density)
            // The scale is a bare multiplier for calc(); every other density token is a measurement.
            sb.Append($"    --shiny-density-{Tokens.Kebab(name)}: {(name == "Scale" ? D(val) : Px(val))};\n");

        sb.Append("\n    /* ===== Spacing ===== */\n");
        foreach (var (name, val) in t.Spacing)
            sb.Append($"    --shiny-spacing-{name.Replace("Space", "")}: {Px(val)};\n");

        sb.Append("\n    /* ===== Type scale ===== */\n");
        // Empty family means "whatever the host app uses", which is what the controls did before
        // typography was themeable — so the default has to stay `inherit`, not a stack of our own.
        var body = string.IsNullOrWhiteSpace(t.TypeSpec.Family) ? "inherit" : t.TypeSpec.Family;
        var display = string.IsNullOrWhiteSpace(t.TypeSpec.DisplayFamily) ? "var(--shiny-type-font-family)" : t.TypeSpec.DisplayFamily;
        var mono = string.IsNullOrWhiteSpace(t.TypeSpec.MonoFamily) ? DefaultMonoStack : t.TypeSpec.MonoFamily;
        sb.Append($"    --shiny-type-font-family: {body};\n");
        sb.Append($"    --shiny-type-font-family-display: {display};\n");
        sb.Append($"    --shiny-type-font-family-mono: {mono};\n");
        // Exposed on its own so off-scale sizes in control CSS can still respond to the theme:
        // font-size: calc(13px * var(--shiny-type-scale, 1)).
        sb.Append($"    --shiny-type-scale: {D(t.TypeSpec.Scale)};\n");
        foreach (var tk in t.Type)
        {
            var k = Tokens.Kebab(tk.Role);
            sb.Append($"    --shiny-type-{k}-size: {Px(tk.Size)};\n");
            sb.Append($"    --shiny-type-{k}-line-height: {Px(tk.LineHeight)};\n");
            sb.Append($"    --shiny-type-{k}-weight: {tk.Weight};\n");
            sb.Append($"    --shiny-type-{k}-tracking: {Px(tk.Tracking)};\n");
        }

        sb.Append("\n    /* ===== Elevation ===== */\n");
        foreach (var (name, shadow) in t.CssElevation)
            sb.Append($"    --shiny-elevation-{name.Replace("Level", "")}: {shadow};\n");

        sb.Append("}\n\n");

        // Dark color overrides — explicit class wins; OS preference applies when unset.
        sb.Append("/* Explicit dark mode (toggle .shiny-theme-dark on <html> or a container) */\n");
        sb.Append(":root.shiny-theme-dark,\n.shiny-theme-dark {\n");
        // color-scheme inherits, so setting it on the scope that carries the dark tokens also flips
        // every native widget underneath it - even when that scope is a div rather than <html>.
        sb.Append("    color-scheme: dark;\n\n");
        foreach (var (role, hex) in t.Dark)
            sb.Append($"    --shiny-color-{Tokens.Kebab(role)}: {hex};\n");
        sb.Append("}\n\n");

        sb.Append("/* Explicit light mode has to restate the scheme: it may sit inside a dark scope */\n");
        sb.Append(":root.shiny-theme-light,\n.shiny-theme-light {\n");
        sb.Append("    color-scheme: light;\n\n");
        foreach (var (role, hex) in t.Light)
            sb.Append($"    --shiny-color-{Tokens.Kebab(role)}: {hex};\n");
        sb.Append("}\n\n");

        sb.Append("/* Follow OS dark preference unless explicitly set to light */\n");
        sb.Append("@media (prefers-color-scheme: dark) {\n");
        sb.Append("    :root:not(.shiny-theme-light) {\n");
        sb.Append("        color-scheme: dark;\n\n");
        foreach (var (role, hex) in t.Dark)
            sb.Append($"        --shiny-color-{Tokens.Kebab(role)}: {hex};\n");
        sb.Append("    }\n}\n");

        return sb.ToString();
    }

    // ============================================================ MAUI ResourceDictionaries

    public static string MauiDictionary(ThemeData t, bool dark)
    {
        var className = $"{t.Name}{(dark ? "Dark" : "Light")}Theme";
        var roles = dark ? t.Dark : t.Light;
        string Role(string name) => roles.First(r => r.Role == name).Hex;

        var shadows = Resolve.MauiElevation(t.ElevationSpec, Role("Primary"), Role("Shadow"));

        var sb = new StringBuilder();
        sb.Append(AutoGen).Append("\n\n");
        sb.Append("using Microsoft.Maui;\n");
        sb.Append("using Microsoft.Maui.Controls;\n");
        sb.Append("using Microsoft.Maui.Graphics;\n\n");
        sb.Append("namespace Shiny.Maui.Controls.Themes;\n\n");
        sb.Append($"/// <summary>{t.Name} theme — {(dark ? "dark" : "light")} scheme resource dictionary.</summary>\n");
        sb.Append($"public partial class {className} : ResourceDictionary\n{{\n");
        sb.Append($"    public {className}()\n    {{\n");

        sb.Append("        // ===== Color =====\n");
        foreach (var (role, hex) in roles)
            sb.Append($"        this.Add(ShinyThemeKeys.Color.{role}, Color.FromArgb(\"{hex}\"));\n");

        sb.Append("\n        // ===== Shape =====\n");
        foreach (var (name, val) in t.Shape)
        {
            sb.Append($"        this.Add(ShinyThemeKeys.Shape.{name}, {D(val)}d);\n");
            // CornerRadius twin: StrokeShape/RoundRectangle properties are typed CornerRadius, and a
            // dynamic resource is assigned verbatim with no conversion, so a double would be dropped.
            sb.Append($"        this.Add(ShinyThemeKeys.Shape.{name}Radius, new CornerRadius({D(val)}d));\n");
        }

        sb.Append("\n        // ===== Border =====\n");
        foreach (var (name, val) in t.Border)
            sb.Append($"        this.Add(ShinyThemeKeys.Border.{name}, {D(val)}d);\n");

        sb.Append("\n        // ===== State =====\n");
        foreach (var (name, val) in t.State)
            sb.Append($"        this.Add(ShinyThemeKeys.State.{name}, {D(val)}d);\n");

        sb.Append("\n        // ===== Density =====\n");
        foreach (var (name, val) in t.Density)
            sb.Append($"        this.Add(ShinyThemeKeys.Density.{name}, {D(val)}d);\n");

        sb.Append("\n        // ===== Spacing =====\n");
        foreach (var (name, val) in t.Spacing)
            sb.Append($"        this.Add(ShinyThemeKeys.Spacing.{name}, {D(val)}d);\n");

        sb.Append("\n        // ===== Type =====\n");
        var family = t.TypeSpec.Family ?? "";
        var displayFamily = string.IsNullOrWhiteSpace(t.TypeSpec.DisplayFamily) ? family : t.TypeSpec.DisplayFamily;
        var monoFamily = t.TypeSpec.MonoFamily ?? "";
        sb.Append($"        this.Add(ShinyThemeKeys.Type.FontFamily, \"{Escape(family)}\");\n");
        sb.Append($"        this.Add(ShinyThemeKeys.Type.FontFamilyDisplay, \"{Escape(displayFamily)}\");\n");
        sb.Append($"        this.Add(ShinyThemeKeys.Type.FontFamilyMono, \"{Escape(monoFamily)}\");\n");
        sb.Append($"        this.Add(ShinyThemeKeys.Type.Scale, {D(t.TypeSpec.Scale)}d);\n");
        foreach (var tk in t.Type)
        {
            sb.Append($"        this.Add(ShinyThemeKeys.Type.{tk.Role}Size, {D(tk.Size)}d);\n");
            // MAUI has no numeric weight on Label, so the scale's weights become the one distinction
            // the platform can actually express.
            sb.Append($"        this.Add(ShinyThemeKeys.Type.{tk.Role}Attributes, FontAttributes.{(tk.Weight >= 600 ? "Bold" : "None")});\n");
        }

        sb.Append("\n        // ===== Elevation =====\n");
        foreach (var s in shadows)
            sb.Append($"        this.Add(ShinyThemeKeys.Elevation.{s.Name}, new Shadow {{ Brush = new SolidColorBrush(Color.FromArgb(\"{s.ColorHex}\")), Offset = new Point({D(s.OffsetX)}d, {D(s.OffsetY)}d), Radius = {D(s.Radius)}f, Opacity = {D(s.Opacity)}f }});\n");

        sb.Append("    }\n}\n");
        return sb.ToString();
    }

    static string Escape(string s) => s.Replace("\\", "\\\\").Replace("\"", "\\\"");

    public static string MauiTheme(ThemeData t)
    {
        var sb = new StringBuilder();
        sb.Append(AutoGen).Append("\n\n");
        sb.Append("using Microsoft.Maui.Controls;\n\n");
        sb.Append("namespace Shiny.Maui.Controls.Themes;\n\n");
        sb.Append($"/// <summary>{t.Description}</summary>\n");
        sb.Append($"public sealed class {t.Name}Theme : IShinyTheme\n{{\n");
        sb.Append($"    public string Name => \"{t.Name}\";\n");
        sb.Append($"    public ResourceDictionary Light {{ get; }} = new {t.Name}LightTheme();\n");
        sb.Append($"    public ResourceDictionary Dark {{ get; }} = new {t.Name}DarkTheme();\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    // ============================================================ ShinyThemeKeys (MAUI contract)

    public static string ThemeKeys()
    {
        var sb = new StringBuilder();
        sb.Append(AutoGen).Append("\n\n");
        sb.Append("namespace Shiny.Maui.Controls.Themes;\n\n");
        sb.Append("/// <summary>Canonical resource keys for Shiny theme tokens. Controls reference these via SetDynamicResource.</summary>\n");
        sb.Append("public static class ShinyThemeKeys\n{\n");

        EmitKeyClass(sb, "Color", "Color", Tokens.ColorRoles);
        EmitKeyClass(sb, "Shape", "Shape", Tokens.Shape.SelectMany(s => new[] { s.Name, s.Name + "Radius" }));
        EmitKeyClass(sb, "Border", "Border", Tokens.BorderNames);
        EmitKeyClass(sb, "State", "State", Tokens.State.Select(s => s.Name));
        EmitKeyClass(sb, "Density", "Density", Tokens.DensityNames);
        EmitKeyClass(sb, "Spacing", "Spacing", Tokens.Spacing.Select(s => s.Name));
        EmitKeyClass(sb, "Type", "Type", Tokens.FontFamilyNames
            .Concat(["Scale"])
            .Concat(Tokens.Type.SelectMany(t => new[] { t.Role + "Size", t.Role + "Attributes" })));
        EmitKeyClass(sb, "Elevation", "Elevation", Tokens.ElevationNames);

        sb.Append("}\n");
        return sb.ToString();
    }

    static void EmitKeyClass(StringBuilder sb, string className, string category, IEnumerable<string> names)
    {
        sb.Append($"    public static class {className}\n    {{\n");
        foreach (var name in names)
            sb.Append($"        public const string {name} = \"Shiny.{category}.{name}\";\n");
        sb.Append("    }\n\n");
    }
}
