using System.Globalization;
using System.Text;

namespace Shiny.ThemeGen;

sealed record ThemeData(
    string Name,
    string Slug,
    string Description,
    IReadOnlyList<(string Role, string Hex)> Light,
    IReadOnlyList<(string Role, string Hex)> Dark,
    IReadOnlyList<(string Name, double Value)> Shape);

static class Emitter
{
    const string AutoGen = "// <auto-generated>\n// Generated by tools/ShinyThemeGen from /themes/*.json. DO NOT EDIT.\n// Edit the source JSON theme and re-run: dotnet run --project tools/ShinyThemeGen\n// </auto-generated>";
    const string AutoGenCss = "/* <auto-generated>\n   Generated by tools/ShinyThemeGen from /themes/*.json. DO NOT EDIT.\n   Edit the source JSON theme and re-run: dotnet run --project tools/ShinyThemeGen\n   </auto-generated> */";

    static string D(double v) => v.ToString("0.####", CultureInfo.InvariantCulture);
    static string Px(double v) => v == 0 ? "0px" : D(v) + "px";

    // ============================================================ Blazor CSS

    public static string Css(ThemeData t)
    {
        var sb = new StringBuilder();
        sb.Append(AutoGenCss).Append("\n\n");

        // Light scheme + all mode-independent tokens live in :root.
        sb.Append(":root {\n");
        sb.Append("    /* ===== Color (light) ===== */\n");
        foreach (var (role, hex) in t.Light)
            sb.Append($"    --shiny-color-{Tokens.Kebab(role)}: {hex};\n");

        sb.Append("\n    /* ===== Shape ===== */\n");
        foreach (var (name, val) in t.Shape)
            sb.Append($"    --shiny-shape-{Tokens.Kebab(name)}: {Px(val)};\n");

        sb.Append("\n    /* ===== State ===== */\n");
        foreach (var (name, val) in Tokens.State)
            sb.Append($"    --shiny-state-{Tokens.Kebab(name)}: {D(val)};\n");

        sb.Append("\n    /* ===== Spacing ===== */\n");
        foreach (var (name, val) in Tokens.Spacing)
            sb.Append($"    --shiny-spacing-{name.Replace("Space", "")}: {Px(val)};\n");

        sb.Append("\n    /* ===== Type scale ===== */\n");
        foreach (var (role, size, lh, weight, tracking) in Tokens.Type)
        {
            var k = Tokens.Kebab(role);
            sb.Append($"    --shiny-type-{k}-size: {Px(size)};\n");
            sb.Append($"    --shiny-type-{k}-line-height: {Px(lh)};\n");
            sb.Append($"    --shiny-type-{k}-weight: {weight};\n");
            sb.Append($"    --shiny-type-{k}-tracking: {Px(tracking)};\n");
        }

        sb.Append("\n    /* ===== Elevation ===== */\n");
        foreach (var (name, shadow) in Tokens.Elevation)
            sb.Append($"    --shiny-elevation-{name.Replace("Level", "")}: {shadow};\n");

        sb.Append("}\n\n");

        // Dark color overrides — explicit class wins; OS preference applies when unset.
        sb.Append("/* Explicit dark mode (toggle .shiny-theme-dark on <html> or a container) */\n");
        sb.Append(":root.shiny-theme-dark,\n.shiny-theme-dark {\n");
        foreach (var (role, hex) in t.Dark)
            sb.Append($"    --shiny-color-{Tokens.Kebab(role)}: {hex};\n");
        sb.Append("}\n\n");

        sb.Append("/* Follow OS dark preference unless explicitly set to light */\n");
        sb.Append("@media (prefers-color-scheme: dark) {\n");
        sb.Append("    :root:not(.shiny-theme-light) {\n");
        foreach (var (role, hex) in t.Dark)
            sb.Append($"        --shiny-color-{Tokens.Kebab(role)}: {hex};\n");
        sb.Append("    }\n}\n");

        return sb.ToString();
    }

    // ============================================================ MAUI ResourceDictionaries

    public static string MauiDictionary(ThemeData t, bool dark)
    {
        var className = $"{t.Name}{(dark ? "Dark" : "Light")}Theme";
        var roles = dark ? t.Dark : t.Light;

        var sb = new StringBuilder();
        sb.Append(AutoGen).Append("\n\n");
        sb.Append("using Microsoft.Maui;\n");
        sb.Append("using Microsoft.Maui.Controls;\n");
        sb.Append("using Microsoft.Maui.Graphics;\n\n");
        sb.Append("namespace Shiny.Maui.Controls.Themes;\n\n");
        sb.Append($"/// <summary>{t.Name} theme — {(dark ? "dark" : "light")} scheme resource dictionary.</summary>\n");
        sb.Append($"public partial class {className} : ResourceDictionary\n{{\n");
        sb.Append($"    public {className}()\n    {{\n");

        sb.Append("        // ===== Color =====\n");
        foreach (var (role, hex) in roles)
            sb.Append($"        this.Add(ShinyThemeKeys.Color.{role}, Color.FromArgb(\"{hex}\"));\n");

        sb.Append("\n        // ===== Shape =====\n");
        foreach (var (name, val) in t.Shape)
            sb.Append($"        this.Add(ShinyThemeKeys.Shape.{name}, {D(val)}d);\n");

        sb.Append("\n        // ===== State =====\n");
        foreach (var (name, val) in Tokens.State)
            sb.Append($"        this.Add(ShinyThemeKeys.State.{name}, {D(val)}d);\n");

        sb.Append("\n        // ===== Spacing =====\n");
        foreach (var (name, val) in Tokens.Spacing)
            sb.Append($"        this.Add(ShinyThemeKeys.Spacing.{name}, {D(val)}d);\n");

        sb.Append("\n        // ===== Type sizes =====\n");
        foreach (var (role, size, _, _, _) in Tokens.Type)
            sb.Append($"        this.Add(ShinyThemeKeys.Type.{role}Size, {D(size)}d);\n");

        sb.Append("\n        // ===== Elevation =====\n");
        foreach (var (name, ox, oy, radius, opacity) in Tokens.MauiShadow)
            sb.Append($"        this.Add(ShinyThemeKeys.Elevation.{name}, new Shadow {{ Brush = new SolidColorBrush(Colors.Black), Offset = new Point({D(ox)}d, {D(oy)}d), Radius = {D(radius)}f, Opacity = {D(opacity)}f }});\n");

        sb.Append("    }\n}\n");
        return sb.ToString();
    }

    public static string MauiTheme(ThemeData t)
    {
        var sb = new StringBuilder();
        sb.Append(AutoGen).Append("\n\n");
        sb.Append("using Microsoft.Maui.Controls;\n\n");
        sb.Append("namespace Shiny.Maui.Controls.Themes;\n\n");
        sb.Append($"/// <summary>{t.Description}</summary>\n");
        sb.Append($"public sealed class {t.Name}Theme : IShinyTheme\n{{\n");
        sb.Append($"    public string Name => \"{t.Name}\";\n");
        sb.Append($"    public ResourceDictionary Light {{ get; }} = new {t.Name}LightTheme();\n");
        sb.Append($"    public ResourceDictionary Dark {{ get; }} = new {t.Name}DarkTheme();\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    // ============================================================ ShinyThemeKeys (MAUI contract)

    public static string ThemeKeys()
    {
        var sb = new StringBuilder();
        sb.Append(AutoGen).Append("\n\n");
        sb.Append("namespace Shiny.Maui.Controls.Themes;\n\n");
        sb.Append("/// <summary>Canonical resource keys for Shiny theme tokens. Controls reference these via SetDynamicResource.</summary>\n");
        sb.Append("public static class ShinyThemeKeys\n{\n");

        EmitKeyClass(sb, "Color", "Color", Tokens.ColorRoles);
        EmitKeyClass(sb, "Shape", "Shape", Tokens.Shape.Select(s => s.Name));
        EmitKeyClass(sb, "State", "State", Tokens.State.Select(s => s.Name));
        EmitKeyClass(sb, "Spacing", "Spacing", Tokens.Spacing.Select(s => s.Name));
        EmitKeyClass(sb, "Type", "Type", Tokens.Type.Select(s => s.Role + "Size"));
        EmitKeyClass(sb, "Elevation", "Elevation", Tokens.MauiShadow.Select(s => s.Name));

        sb.Append("}\n");
        return sb.ToString();
    }

    static void EmitKeyClass(StringBuilder sb, string className, string category, IEnumerable<string> names)
    {
        sb.Append($"    public static class {className}\n    {{\n");
        foreach (var name in names)
            sb.Append($"        public const string {name} = \"Shiny.{category}.{name}\";\n");
        sb.Append("    }\n\n");
    }
}
