using Shiny.Blazor.Controls.MotionIcons;
using Shiny.Controls.MotionIcons;

namespace Shiny.Controls.MotionIcons.Tests;

/// <summary>
/// Covers the compiled stylesheet — the half of the parity story that only exists on the web.
/// </summary>
public class MotionCssTests
{
    static MotionPlan PlanFor(string icon, MotionPreset preset = MotionPreset.Default)
    {
        var definition = MotionIconLibrary.Get(icon);
        var spec = MotionResolver.ResolveMotion(definition, preset)!;

        return MotionPlan.For(definition, spec);
    }

    [Fact]
    public void EveryIconCompiles()
    {
        foreach (var icon in MotionIconLibrary.All)
        {
            var spec = MotionResolver.ResolveMotion(icon, MotionPreset.Default)!;
            var plan = MotionPlan.For(icon, spec);

            plan.Css.ShouldNotBeNullOrWhiteSpace();
            plan.Markup.ShouldContain("<path");
            plan.Css.ShouldContain("@keyframes");
        }
    }

    [Fact]
    public void EveryPresetCompilesForEveryIcon()
    {
        foreach (var preset in Enum.GetValues<MotionPreset>())
        {
            foreach (var icon in MotionIconLibrary.All)
            {
                var spec = MotionResolver.ResolveMotion(icon, preset);

                if (spec is null)
                {
                    preset.ShouldBe(MotionPreset.None);
                    continue;
                }

                MotionPlan.For(icon, spec).Css.ShouldNotBeNullOrWhiteSpace();
            }
        }
    }

    [Fact]
    public void BracesBalance()
    {
        // A stylesheet is injected raw into the page; an unbalanced brace would not throw anywhere,
        // it would silently swallow the rules that came after it.
        foreach (var icon in MotionIconLibrary.All)
        {
            var spec = MotionResolver.ResolveMotion(icon, MotionPreset.Default)!;
            var css = MotionPlan.For(icon, spec).Css;

            css.Count(c => c == '{').ShouldBe(css.Count(c => c == '}'), $"{icon.Name} has unbalanced braces");
        }
    }

    [Fact]
    public void MarkupTagsBalance()
    {
        foreach (var icon in MotionIconLibrary.All)
        {
            var spec = MotionResolver.ResolveMotion(icon, MotionPreset.Default)!;
            var markup = MotionPlan.For(icon, spec).Markup;

            CountOccurrences(markup, "<g ").ShouldBe(CountOccurrences(markup, "</g>"), $"{icon.Name} has unbalanced groups");
            CountOccurrences(markup, "<path").ShouldBe(icon.Parts.Count);
        }
    }

    [Fact]
    public void KeyframeOffsetsAreOrderedAndBounded()
    {
        foreach (var icon in MotionIconLibrary.All)
        {
            var spec = MotionResolver.ResolveMotion(icon, MotionPreset.Default)!;
            var css = MotionPlan.For(icon, spec).Css;

            foreach (var block in Blocks(css, "@keyframes"))
            {
                var offsets = Offsets(block);

                offsets.ShouldNotBeEmpty();
                offsets[0].ShouldBe(0d, 0.001d);
                offsets[^1].ShouldBe(100d, 0.001d);

                for (var i = 1; i < offsets.Count; i++)
                    offsets[i].ShouldBeGreaterThan(offsets[i - 1]);
            }
        }
    }

    [Fact]
    public void EveryAnimationIsMatchedByAnElementInTheMarkup()
    {
        // The stylesheet and the SVG are generated by two different files that have to agree on
        // every class name. A mismatch fails nowhere: the rule is simply never matched, and the icon
        // quietly loses that piece of its motion. This caught exactly that — the whole-icon groups
        // were being named rt/rs in the markup and tr/sr in the CSS.
        foreach (var icon in MotionIconLibrary.All)
        {
            foreach (var preset in Enum.GetValues<MotionPreset>())
            {
                var spec = MotionResolver.ResolveMotion(icon, preset);

                if (spec is null)
                    continue;

                var plan = MotionPlan.For(icon, spec);

                foreach (var animated in AnimatedClasses(plan))
                {
                    plan.Markup.ShouldContain($"mi-{animated}\"",
                        customMessage: $"{icon.Name} + {preset}: nothing in the SVG carries mi-{animated}");
                }
            }
        }
    }

    [Fact]
    public void EveryAnimatedElementInTheMarkupHasAnAnimation()
    {
        // And the other direction: a group in the SVG with no keyframes behind it is a wasted
        // element, and a sign the plan and the compiler have drifted apart.
        foreach (var icon in MotionIconLibrary.All)
        {
            var spec = MotionResolver.ResolveMotion(icon, MotionPreset.Default)!;
            var plan = MotionPlan.For(icon, spec);
            var animated = AnimatedClasses(plan).ToHashSet(StringComparer.Ordinal);

            foreach (var used in MarkupClasses(plan.Markup))
                animated.ShouldContain(used, $"{icon.Name}: mi-{used} is in the SVG but has no keyframes");
        }
    }

    static IEnumerable<string> AnimatedClasses(MotionPlan plan)
    {
        var marker = "@keyframes " + plan.Scope + "-";
        var index = 0;

        while ((index = plan.Css.IndexOf(marker, index, StringComparison.Ordinal)) >= 0)
        {
            var start = index + marker.Length;
            var end = plan.Css.IndexOf('{', start);

            yield return plan.Css[start..end];
            index = end;
        }
    }

    static IEnumerable<string> MarkupClasses(string markup)
    {
        // Every element carrying mi-a is claiming to be animated; the class beside it names which.
        foreach (var chunk in markup.Split("class=\"").Skip(1))
        {
            var classes = chunk[..chunk.IndexOf('"')].Split(' ');

            if (!classes.Contains("mi-a"))
                continue;

            foreach (var css in classes)
            {
                if (css is not ("mi-a" or "mi-g") && css.StartsWith("mi-", StringComparison.Ordinal))
                    yield return css[3..];
            }
        }
    }

    [Fact]
    public void TransformChannelsGetTheirOwnNestedGroup()
    {
        // CSS has one transform property per element, so a part that both rotates and scales has to
        // be wrapped twice — if these ever collapsed onto one element, one of the two animations
        // would silently win and the icon would lose half its motion.
        var plan = PlanFor("star");

        plan.Markup.ShouldContain("mi-rr");
        plan.Markup.ShouldContain("mi-rs");
        plan.Css.ShouldContain("rotate(");
        plan.Css.ShouldContain("scale(");
    }

    [Fact]
    public void TranslationChannelsShareOneAnimation()
    {
        // X and Y are two tracks but one CSS property, so they must merge into a single translate()
        // rather than producing two competing animations on the same element.
        var plan = PlanFor("search");

        plan.Css.ShouldContain("translate(");
        CountOccurrences(plan.Css, "@keyframes " + plan.Scope + "-rt{").ShouldBe(1);
    }

    [Fact]
    public void TrimmedPartsGetANormalisedDashPattern()
    {
        var plan = PlanFor("check");

        plan.Markup.ShouldContain("pathLength=\"1\"");
        plan.Markup.ShouldContain("stroke-dasharray=\"1 1\"");
        plan.Css.ShouldContain("stroke-dashoffset");
    }

    [Fact]
    public void UntrimmedPartsDoNotGetADashPattern()
        => PlanFor("heart").Markup.ShouldNotContain("stroke-dasharray");

    [Fact]
    public void CurvesWithoutACssKeywordAreSampled()
    {
        // BounceOut has no keyword, so it has to arrive as linear() — preceded by a keyword
        // fallback for browsers that cannot parse it.
        var css = PlanFor("chevron-down").Css;

        css.ShouldContain("linear(");
        css.ShouldContain("animation-timing-function:ease-out;animation-timing-function:linear(");
    }

    [Fact]
    public void InstanceValuesStayOutOfTheStylesheet()
    {
        // Size, colour, duration and repeat count all ride in as custom properties. If any of them
        // leaked into the generated CSS, every instance would need its own copy of it.
        var css = PlanFor("bell").Css;

        css.ShouldContain("var(--shiny-mi-duration)");
        css.ShouldContain("var(--shiny-mi-iterations)");
        css.ShouldNotContain("#");
    }

    [Fact]
    public void IdenticalMotionSharesOneCompiledStylesheet()
    {
        var icon = MotionIconLibrary.Get("bell");
        var spec = MotionResolver.ResolveMotion(icon, MotionPreset.Default)!;

        MotionPlan.For(icon, spec).ShouldBeSameAs(MotionPlan.For(icon, spec));
    }

    [Fact]
    public void RetimingDoesNotProduceASecondStylesheet()
    {
        // Duration is a custom property, so the same motion at two speeds is one stylesheet.
        var icon = MotionIconLibrary.Get("bell");

        var fast = MotionResolver.ResolveMotion(icon, MotionPreset.Default, TimeSpan.FromMilliseconds(200))!;
        var slow = MotionResolver.ResolveMotion(icon, MotionPreset.Default, TimeSpan.FromSeconds(4))!;

        MotionPlan.For(icon, fast).Scope.ShouldBe(MotionPlan.For(icon, slow).Scope);
    }

    [Fact]
    public void AnIntervalDoesProduceADifferentStylesheet()
    {
        // A resting gap is folded into the keys, so it genuinely is different motion.
        var icon = MotionIconLibrary.Get("bell");

        var tight = MotionResolver.ResolveMotion(icon, MotionPreset.Default)!;
        var spaced = MotionResolver.ResolveMotion(icon, MotionPreset.Default, null, TimeSpan.FromSeconds(2))!;

        MotionPlan.For(icon, spaced).Scope.ShouldNotBe(MotionPlan.For(icon, tight).Scope);
    }

    [Fact]
    public void CallerSuppliedPathDataIsEscaped()
    {
        var icon = MotionIconLibrary.FromPath("M0 0h10\"><script>alert(1)</script>");
        var spec = MotionResolver.ResolveMotion(icon, MotionPreset.Pulse)!;

        var markup = MotionPlan.For(icon, spec).Markup;

        markup.ShouldNotContain("<script>");
        markup.ShouldContain("&quot;");
    }

    static int CountOccurrences(string haystack, string needle)
    {
        var count = 0;
        var index = 0;

        while ((index = haystack.IndexOf(needle, index, StringComparison.Ordinal)) >= 0)
        {
            count++;
            index += needle.Length;
        }

        return count;
    }

    static IEnumerable<string> Blocks(string css, string keyword)
    {
        var index = 0;

        while ((index = css.IndexOf(keyword, index, StringComparison.Ordinal)) >= 0)
        {
            var open = css.IndexOf('{', index);
            var depth = 0;
            var end = open;

            for (; end < css.Length; end++)
            {
                if (css[end] == '{')
                    depth++;
                else if (css[end] == '}' && --depth == 0)
                    break;
            }

            yield return css[open..end];
            index = end;
        }
    }

    static List<double> Offsets(string block)
    {
        var offsets = new List<double>();
        var index = 0;

        while ((index = block.IndexOf('%', index)) >= 0)
        {
            var start = index;

            while (start > 0 && (char.IsDigit(block[start - 1]) || block[start - 1] == '.'))
                start--;

            if (start < index)
                offsets.Add(double.Parse(block[start..index], System.Globalization.CultureInfo.InvariantCulture));

            index++;
        }

        return offsets;
    }
}
