<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <RootNamespace>Sample.Blazor</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Shiny.Blazor.Controls.SpeechAddins\Shiny.Blazor.Controls.SpeechAddins.csproj" />
        <ProjectReference Include="..\..\src\Shiny.Blazor.Controls\Shiny.Blazor.Controls.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.Blazor.Controls.Markdown\Shiny.Blazor.Controls.Markdown.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.Blazor.Controls.MermaidDiagrams\Shiny.Blazor.Controls.MermaidDiagrams.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.Blazor.Controls.Barcodes\Shiny.Blazor.Controls.Barcodes.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.Blazor.Controls.Camera\Shiny.Blazor.Controls.Camera.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.Blazor.Controls.Camera.Ai\Shiny.Blazor.Controls.Camera.Ai.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.Blazor.Controls.Kiosk\Shiny.Blazor.Controls.Kiosk.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.Blazor.Controls.Themes.Ocean\Shiny.Blazor.Controls.Themes.Ocean.csproj"/>
        <ProjectReference Include="..\..\src\Shiny.Blazor.Controls.Themes.Material\Shiny.Blazor.Controls.Themes.Material.csproj"/>
    </ItemGroup>
</Project>
